exclude: tutorials|judge-server
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.28.0
    hooks:
      # Have to have separate configs for TypeScript projects, because of project-specific
      # tsconfigs.
      - id: eslint
        name: eslint - client
        types: [file]
        args: [--fix, --config, web-client/.eslintrc.json]
        files: ^web-client/src/.*\.[jt]sx?$
